#pragma once

#include <map>
#include <unordered_map>
#include <vector>
#include <string>
#include <sstream>
#include <set>
#include <stdint.h>
#include <tuple>
#include <unordered_set>
#include <utility>
#include <chrono>
#include <algorithm>
#include <functional>
#include <array>
#include <bitset>
#include <ctype.h>
#include <malloc.h>
#include <math.h>
#include <deque>
#include <queue>
#include <stack>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <memory>
#include <random>
#include <typeinfo>
#include <optional>
#include <forward_list>
#include <ostream>
#include <cstring>
#include <span>
#include <ranges>

namespace chrono = std::chrono;

using std::map;
using std::optional;
using std::vector;
using std::array;
using std::span;
using std::pair;
using std::function;
using std::string;
using std::to_string;
using std::reference_wrapper;
using std::unordered_map;
using std::set;
using std::stack;
using std::nullopt;
using std::is_integral;
using std::is_same;
using std::remove_reference;
using std::integral_constant;
