/*
 * Pin.cpp
 *
 *  Created on: 19 oct. 2022
 *      Author: stefan
 */

#include "PinModel/Pin.hpp"

Pin::Pin(){}

Pin::Pin(GPIOPort port, GPIOPin gpio_pin) : port((GPIO_TypeDef*)port), gpio_pin(gpio_pin){}

Pin PE2(GPIOPort::PORT_E,GPIOPin::PIN_2);
Pin PE3(GPIOPort::PORT_E,GPIOPin::PIN_3);
Pin PE4(GPIOPort::PORT_E,GPIOPin::PIN_4);
Pin PE5(GPIOPort::PORT_E,GPIOPin::PIN_5);
Pin PE6(GPIOPort::PORT_E,GPIOPin::PIN_6);
Pin PC13(GPIOPort::PORT_C,GPIOPin::PIN_13);
Pin PC14(GPIOPort::PORT_C,GPIOPin::PIN_14);
Pin PC15(GPIOPort::PORT_C,GPIOPin::PIN_15);
Pin PF0(GPIOPort::PORT_F,GPIOPin::PIN_0);
Pin PF1(GPIOPort::PORT_F,GPIOPin::PIN_1);
Pin PF2(GPIOPort::PORT_F,GPIOPin::PIN_2);
Pin PF3(GPIOPort::PORT_F,GPIOPin::PIN_3);
Pin PF4(GPIOPort::PORT_F,GPIOPin::PIN_4);
Pin PF5(GPIOPort::PORT_F,GPIOPin::PIN_5);
Pin PF6(GPIOPort::PORT_F,GPIOPin::PIN_6);
Pin PF7(GPIOPort::PORT_F,GPIOPin::PIN_7);
Pin PF8(GPIOPort::PORT_F,GPIOPin::PIN_8);
Pin PF9(GPIOPort::PORT_F,GPIOPin::PIN_9);
Pin PF10(GPIOPort::PORT_F,GPIOPin::PIN_10);
Pin PH0(GPIOPort::PORT_H,GPIOPin::PIN_0);
Pin PH1(GPIOPort::PORT_H,GPIOPin::PIN_1);
Pin PC0(GPIOPort::PORT_C,GPIOPin::PIN_0);
Pin PC1(GPIOPort::PORT_C,GPIOPin::PIN_1);
Pin PC2(GPIOPort::PORT_C,GPIOPin::PIN_2);
Pin PC3(GPIOPort::PORT_C,GPIOPin::PIN_3);
Pin PA0(GPIOPort::PORT_A,GPIOPin::PIN_0);
Pin PA1(GPIOPort::PORT_A,GPIOPin::PIN_1);
Pin PA2(GPIOPort::PORT_A,GPIOPin::PIN_2);
Pin PA3(GPIOPort::PORT_A,GPIOPin::PIN_3);
Pin PA4(GPIOPort::PORT_A,GPIOPin::PIN_4);
Pin PA5(GPIOPort::PORT_A,GPIOPin::PIN_5);
Pin PA6(GPIOPort::PORT_A,GPIOPin::PIN_6);
Pin PA7(GPIOPort::PORT_A,GPIOPin::PIN_7);
Pin PC4(GPIOPort::PORT_C,GPIOPin::PIN_4);
Pin PC5(GPIOPort::PORT_C,GPIOPin::PIN_5);
Pin PB0(GPIOPort::PORT_B,GPIOPin::PIN_0);
Pin PB1(GPIOPort::PORT_B,GPIOPin::PIN_1);
Pin PB2(GPIOPort::PORT_B,GPIOPin::PIN_2);
Pin PF11(GPIOPort::PORT_F,GPIOPin::PIN_11);
Pin PF12(GPIOPort::PORT_F,GPIOPin::PIN_12);
Pin PF13(GPIOPort::PORT_F,GPIOPin::PIN_13);
Pin PF14(GPIOPort::PORT_F,GPIOPin::PIN_14);
Pin PF15(GPIOPort::PORT_F,GPIOPin::PIN_15);
Pin PG0(GPIOPort::PORT_G,GPIOPin::PIN_0);
Pin PG1(GPIOPort::PORT_G,GPIOPin::PIN_1);
Pin PE7(GPIOPort::PORT_E,GPIOPin::PIN_7);
Pin PE8(GPIOPort::PORT_E,GPIOPin::PIN_8);
Pin PE9(GPIOPort::PORT_E,GPIOPin::PIN_9);
Pin PE10(GPIOPort::PORT_E,GPIOPin::PIN_10);
Pin PE11(GPIOPort::PORT_E,GPIOPin::PIN_11);
Pin PE12(GPIOPort::PORT_E,GPIOPin::PIN_12);
Pin PE13(GPIOPort::PORT_E,GPIOPin::PIN_13);
Pin PE14(GPIOPort::PORT_E,GPIOPin::PIN_14);
Pin PE15(GPIOPort::PORT_E,GPIOPin::PIN_15);
Pin PB10(GPIOPort::PORT_B,GPIOPin::PIN_10);
Pin PB11(GPIOPort::PORT_B,GPIOPin::PIN_11);
Pin PB12(GPIOPort::PORT_B,GPIOPin::PIN_12);
Pin PB13(GPIOPort::PORT_B,GPIOPin::PIN_13);
Pin PB14(GPIOPort::PORT_B,GPIOPin::PIN_14);
Pin PB15(GPIOPort::PORT_B,GPIOPin::PIN_15);
Pin PD8(GPIOPort::PORT_D,GPIOPin::PIN_8);
Pin PD9(GPIOPort::PORT_D,GPIOPin::PIN_9);
Pin PD10(GPIOPort::PORT_D,GPIOPin::PIN_10);
Pin PD11(GPIOPort::PORT_D,GPIOPin::PIN_11);
Pin PD12(GPIOPort::PORT_D,GPIOPin::PIN_12);
Pin PD13(GPIOPort::PORT_D,GPIOPin::PIN_13);
Pin PD14(GPIOPort::PORT_D,GPIOPin::PIN_14);
Pin PD15(GPIOPort::PORT_D,GPIOPin::PIN_15);
Pin PG2(GPIOPort::PORT_G,GPIOPin::PIN_2);
Pin PG3(GPIOPort::PORT_G,GPIOPin::PIN_3);
Pin PG4(GPIOPort::PORT_G,GPIOPin::PIN_4);
Pin PG5(GPIOPort::PORT_G,GPIOPin::PIN_5);
Pin PG6(GPIOPort::PORT_G,GPIOPin::PIN_6);
Pin PG7(GPIOPort::PORT_G,GPIOPin::PIN_7);
Pin PG8(GPIOPort::PORT_G,GPIOPin::PIN_8);
Pin PC6(GPIOPort::PORT_C,GPIOPin::PIN_6);
Pin PC7(GPIOPort::PORT_C,GPIOPin::PIN_7);
Pin PC8(GPIOPort::PORT_C,GPIOPin::PIN_8);
Pin PC9(GPIOPort::PORT_C,GPIOPin::PIN_9);
Pin PA8(GPIOPort::PORT_A,GPIOPin::PIN_8);
Pin PA9(GPIOPort::PORT_A,GPIOPin::PIN_9);
Pin PA10(GPIOPort::PORT_A,GPIOPin::PIN_10);
Pin PA11(GPIOPort::PORT_A,GPIOPin::PIN_11);
Pin PA12(GPIOPort::PORT_A,GPIOPin::PIN_12);
Pin PC10(GPIOPort::PORT_C,GPIOPin::PIN_10);
Pin PC11(GPIOPort::PORT_C,GPIOPin::PIN_11);
Pin PC12(GPIOPort::PORT_C,GPIOPin::PIN_12);
Pin PD0(GPIOPort::PORT_D,GPIOPin::PIN_0);
Pin PD1(GPIOPort::PORT_D,GPIOPin::PIN_1);
Pin PD2(GPIOPort::PORT_D,GPIOPin::PIN_2);
Pin PD3(GPIOPort::PORT_D,GPIOPin::PIN_3);
Pin PD4(GPIOPort::PORT_D,GPIOPin::PIN_4);
Pin PD5(GPIOPort::PORT_D,GPIOPin::PIN_5);
Pin PD6(GPIOPort::PORT_D,GPIOPin::PIN_6);
Pin PD7(GPIOPort::PORT_D,GPIOPin::PIN_7);
Pin PG9(GPIOPort::PORT_G,GPIOPin::PIN_9);
Pin PG10(GPIOPort::PORT_G,GPIOPin::PIN_10);
Pin PG11(GPIOPort::PORT_G,GPIOPin::PIN_11);
Pin PG12(GPIOPort::PORT_G,GPIOPin::PIN_12);
Pin PG13(GPIOPort::PORT_G,GPIOPin::PIN_13);
Pin PG14(GPIOPort::PORT_G,GPIOPin::PIN_14);
Pin PG15(GPIOPort::PORT_G,GPIOPin::PIN_15);
Pin PB4(GPIOPort::PORT_B,GPIOPin::PIN_4);
Pin PB5(GPIOPort::PORT_B,GPIOPin::PIN_5);
Pin PB6(GPIOPort::PORT_B,GPIOPin::PIN_6);
Pin PB7(GPIOPort::PORT_B,GPIOPin::PIN_7);
Pin PB8(GPIOPort::PORT_B,GPIOPin::PIN_8);
Pin PB9(GPIOPort::PORT_B,GPIOPin::PIN_9);
Pin PE0(GPIOPort::PORT_E,GPIOPin::PIN_0);
Pin PE1(GPIOPort::PORT_E,GPIOPin::PIN_1);

vector<reference_wrapper<Pin>> Pin::pinVector = {PA0,PA1,PA10,PA11,PA12,
PA9,PB0,PB1,PB10,PB11,PB12,PB13,PB14,PB15,PB2,PB4,PB5,PB6,PB7,PB8,PB9,PC0,PC1,PC10,
PC11,PC12,PC13,PC14,PC15,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PD0,PD1,PD10,PD11,PD12,PD13,
PD14,PD15,PD2,PD3,PD4,PD5,PD6,PD7,PD8,PD9,PE0,PE1,PE10,PE11,PE12,PE13,PE14,PE15,PE2,PE3,
PE4,PE5,PE6,PE7,PE8,PE9,PF0,PF1,PF10,PF11,PF12,PF13,PF14,PF15,PF2,PF3,PF4,PF5,PF6,PF7,
PF8,PF9,PG0,PG1,PG10,PG11,PG12,PG13,PG14,PG15,PG2,PG3,PG4,PG5,PG6,PG7,PG8,PG9,PH0,PH1,
PA2,PA3,PA4,PA5,PA6,PA7,PA8};

void Pin::inscribe(Pin& pin, OperationMode mode){
	if(pin.mode != OperationMode::NOT_USED){
		return;
	}
	pin.mode = mode;
}

void Pin::start(){
	GPIO_InitTypeDef GPIO_InitStruct;
	__HAL_RCC_GPIOB_CLK_ENABLE();
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_GPIOC_CLK_ENABLE();
	__HAL_RCC_GPIOD_CLK_ENABLE();
	__HAL_RCC_GPIOE_CLK_ENABLE();
	__HAL_RCC_GPIOF_CLK_ENABLE();
	__HAL_RCC_GPIOG_CLK_ENABLE();

	for(Pin& pin : Pin::pinVector){
		GPIO_InitStruct = {0};
		GPIO_InitStruct.Pin = pin.gpio_pin;
		switch(pin.mode){

		case OperationMode::NOT_USED:
			GPIO_InitStruct.Mode =  GPIO_MODE_INPUT;
			GPIO_InitStruct.Pull = GPIO_PULLDOWN;
			HAL_GPIO_Init(pin.port, &GPIO_InitStruct);
			break;

		case OperationMode::OUTPUT:
			GPIO_InitStruct.Mode =  GPIO_MODE_OUTPUT_PP;
			GPIO_InitStruct.Pull = GPIO_NOPULL;
			GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
			HAL_GPIO_Init(pin.port, &GPIO_InitStruct);
			break;

		case OperationMode::INPUT:
			GPIO_InitStruct.Mode =  GPIO_MODE_INPUT;
			GPIO_InitStruct.Pull = GPIO_NOPULL;
			HAL_GPIO_Init(pin.port, &GPIO_InitStruct);
			break;

		case OperationMode::ANALOG:
			GPIO_InitStruct.Mode =  GPIO_MODE_ANALOG;
			GPIO_InitStruct.Pull = GPIO_NOPULL;
			HAL_GPIO_Init(pin.port, &GPIO_InitStruct);
			break;
		case OperationMode::EXTERNAL_INTERRUPT:
			GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
			GPIO_InitStruct.Pull = GPIO_PULLDOWN;
			HAL_GPIO_Init(pin.port, &GPIO_InitStruct);
			break;
		case OperationMode::PWM_MODE:
			GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
			GPIO_InitStruct.Pull = GPIO_NOPULL;
			GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
			GPIO_InitStruct.Alternate = GPIO_AF1_TIM1;
			HAL_GPIO_Init(pin.port, &GPIO_InitStruct);
			break;

		default:
			break;
		}
	}
}







