#pragma once

#include "DigitalOutputservice/DigitalOutputservice.hpp"
#include "DigitalInputService/DigitalInputService.hpp"
#include "Flash/Flash.hpp"
#include "Flash/FlashTests/Flash_Test.hpp"
#include "ADC/ADC.hpp"
#include "PWMservice/PWMservice.hpp"
#include "Time/Time.hpp"
#include "InputCapture/InputCapture.hpp"
#include "Encoder/Encoder.hpp"
#include "EXTI/EXTI.hpp"
#include "Communication/SPI/SPI.hpp"
#include "Communication/UART/UART.hpp"
#include "Communication/Ethernet/UDP/DatagramSocket.hpp"
#include "Communication/Ethernet/TCP/ServerSocket.hpp"
#include "Communication/Ethernet/TCP/Socket.hpp"
#include "Communication/Ethernet/Ethernet.hpp"
