/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     21/10/2022 11:26:50
  * @brief    Default under dev library file.
  ******************************************************************************
*/

#include "ST-LIB.hpp"

void STLIB::start(TARGET target, string ip, string subnet_mask, string gateway, UART::Peripheral& printf_peripheral) {
	HALAL::start(target, ip, subnet_mask, gateway, printf_peripheral);
}

void STLIB::update() {
    Ethernet::update();
	ErrorHandlerModel::ErrorHandlerUpdate();
}
